
class EConstruction:
    # production
    SMELTER = 'Smelter'
    FOUNDRY = 'Foundry'
    CONSTRUCTOR = 'Constructor'
    ASSEMBLER = 'Assembler'
    MANUFACTURER = 'Manufacturer'
    REFINERY = 'Refinery'
    PACKAGER = 'Packager'
    BLENDER = 'Blender'
    PARTICULE_ACCELERATOR = 'Particule Accelerator'
    # logistic
    CONVEYORSPLITER = 'Conveyor_Spliter'
    CONVEYORMERGER = 'Conveyor_Merger'
    # extractor
    MINERMK1 = 'Miner_Mk.1'
    MINERMK2 = 'Miner_Mk.2'
    MINERMK3 = 'Miner_Mk.3'
    OILEXTRACTOR = 'Oil_Extractor'
    WATEREXTRACTOR = 'Water_Extractor'
    RESSOURCEWELLPRESSURIZER = 'Ressource-well_Pressurizer'
    RESSOURCEWELLEXTRACTOR = 'Ressource-well_Extractor'

class ERessource:
    # ORES
    LIMESTONE = 'Limestone'
    IRON_ORE = 'Iron_Ore'
    COPPER_ORE = 'Copper_Ore'
    CATERIUM_ORE = 'Caterium_Ore'
    COAL = 'Coal'
    RAW_QUARTZ = 'Raw_Quartz'
    SULFUR = 'Sulfur'
    BAUXITE = 'Bauxite'
    SAM_ORE = 'S.A.M. Ore'
    URANIUM = 'Uranium'
    # INGOTS
    IRON_INGOT = 'Iron_Ingot'
    COPPER_INGOT = 'Copper_Ingot'
    CATERIUM_INGOT = 'Caterium_Ingot'
    STEEL_INGOT = 'Steel_Ingot'
    ALUMINUM_INGOT = 'Aluminum_Ingot'
    # MINERALS
    CONCRETE = 'Concrete'
    QUARTZ_CRYSTAL = 'Quartz_Crystal'
    SILICA = 'Silica'
    COPPER_POWDER = 'Copper_Powder'
    POLYMER_RESIN = 'Polymer_Resin'
    PETROLEUM_COKE = 'Petroleum_Coke'
    ALUMINUM_SCRAP = 'Aluminum_Scrap'
    # ALIENS
    ALIEN_PROTEIN = 'Alien_Protein'
    ALIEN_DNA_CAPSULE = 'Alien_DNA_Capsule'
    # LIQUIDS
    WATER = 'Water'
    CRUDE_OIL = 'Crude_Oil'
    HEAVY_OIL_RESIDUE = 'Heavy_Oil_Residue'
    FUEL = 'Fuel'
    LIQUID_BIOFUEL = 'Liquid_Biofuel'
    TURBOFUEL = 'Turbofuel'
    ALUMINA_SOLUTION = 'Alumina_Solution'
    SULFURIC_ACID = 'Sulfuric_Acid'
    NITRIC_ACID = 'Nitric_Acid'
    # GAS
    NITROGEN_GAS = 'Nitrogen_Gas'
    # STANDARD_PARTS
    IRON_ROD = 'Iron_Rod'
    SCREW = 'Screw'
    IRON_PLATE = 'Iron_Plate'
    REINFORCED_IRON_PLATE = 'Reinforced_Iron_Plate'
    COPPER_SHEET = 'Copper_Sheet'
    ALCLAD_ALUMINUM_SHEET = 'Alclad_Aluminum_Sheet'
    ALUMINUM_CASING = 'Aluminum_Casing'
    STEEL_PIPE = 'Steel_Pipe'
    STEEL_BEAM = 'Steel_Beam'
    ENCASED_INDUSTRIAL_BEAM = 'Encased_Industrial_Beam'
    MODULAR_FRAME = 'Modular_Frame'
    HEAVY_MODULAR_FRAME = 'Heavy_Modular_Frame'
    FUSED_MODULAR_FRAME = 'Fused_Modular_Frame'
    FABRIC = 'Fabric'
    PLASTIC = 'Plastic'
    RUBBER = 'Rubber'
    # INDUSTRIAL_PARTS
    ROTOR = 'Rotor'
    STATOR = 'Stator'
    BATTERY = 'Battery'
    MOTOR = 'Motor'
    HEAT_SINK = 'Heat_Sink'
    COOLING_SYSTEM = 'Cooling_System'
    TURBO_MOTOR = 'Turbo_Motor'
    # ELECTRONICS
    WIRE = 'Wire'
    CABLE = 'Cable'
    QUICKWIRE = 'Quickwire'
    CIRCUIT_BOARD = 'Circuit_Board'
    AI_LIMITER = 'AI_Limiter'
    HIGHSPEED_CONNECTOR = 'High-Speed_Connector'
    # COMMUNICATIONS
    COMPUTER = 'Computer'
    SUPERCOMPUTER = 'Supercomputer'
    QUANTUM_COMPUTER = 'Quantum_Computer'
    RADIO_CONTROL_UNIT = 'Radio_Control_Unit'
    CRYSTAL_OSCILLATOR = 'Crystal_Oscillator'
    SUPERPOSITION_OSCILLATOR = 'Superposition_Oscillator'
    # CONTAINERS
    EMPTY_CANISTER = 'Empty_Canister'
    EMPTY_FLUID_TANK = 'Empty_Fluid_Tank'
    PRESSURE_CONVERSION_CUBE = 'Pressure_Conversion_Cube'
    PACKAGED_WATER = 'Packaged_Water'
    PACKAGED_ALUMINA_SOLUTION = 'Packaged_Alumina_Solution'
    PACKAGED_SULFURIC_ACID = 'Packaged_Sulfuric_Acid'
    PACKAGED_NITRIC_ACID = 'Packaged_Nitric_Acid'
    PACKAGED_NITROGEN_GAS = 'Packaged_Nitrogen_Gas'
    # FUELS
    LEAVES = 'Leaves'
    MYCELIA = 'Mycelia'
    FLOWER_PETALS = 'Flower_Petals'
    WOOD = 'Wood'
    BIOMASS = 'Biomass'
    COMPACTED_COAL = 'Compacted_Coal'
    PACKAGED_OIL = 'Packaged_Oil'
    PACKAGED_HEAVY_OIL_RESIDUE = 'Packaged_Heavy_Oil_Residue'
    SOLID_BIOFUEL = 'Solid_Biofuel'
    PACKAGED_FUEL = 'Packaged_Fuel'
    PACKAGED_LIQUID_BIOFUEL = 'Packaged_Liquid_Biofuel'
    PACKAGED_TURBOFUEL = 'Packaged_Turbofuel'
    URANIUM_FUEL_ROD = 'Uranium_Fuel_Rod'
    PLUTONIUM_FUEL_ROD = 'Plutonium_Fuel_Rod'
    # CONSUMED
    BLACK_POWDER = 'Black_Powder'
    SMOKELESS_POWDER = 'Smokeless_Powder'
    GAS_FILTER = 'Gas_Filter'
    COLOR_CARTRIDGE = 'Color_Cartridge'
    BEACON = 'Beacon'
    IODINE_INFUSED_FILTER = 'Iodine_Infused_Filter'
    # AMMOS
    IRON_REBAR = 'Iron_Rebar'
    STUN_REBAR = 'Stun_Rebar'
    SHATTER_REBAR = 'Shatter_Rebar'
    EXPLOSIVE_REBAR = 'Explosive_Rebar'
    RIFLE_AMMO = 'Rifle_Ammo'
    HOMING_RIFLE_AMMO = 'Homing_Rifle_Ammo'
    TURBO_RIFLE_AMMO = 'Turbo_Rifle_Ammo'
    RIFLE_CARTRIDGE = 'Rifle_Cartridge'
    NOBELISK = 'Nobelisk'
    GAS_NOBELISK = 'Gas_Nobelisk'
    PULSE_NOBELISK = 'Pulse_Nobelisk'
    CLUSTER_NOBELISK = 'Cluster_Nobelisk'
    NUKE_NOBELISK = 'Nuke_Nobelisk'
    # NUCLEAR
    ELECTROMAGNETIC_CONTROL_ROD = 'Electromagnetic_Control_Rod'
    ENCASED_URANIUM_CELL = 'Encased_Uranium_Cell'
    NONFISSILE_URANIUM = 'Non-fissile_Uranium'
    PLUTONIUM_PELLET = 'Plutonium_Pellet'
    ENCASED_PLUTONIUM_CELL = 'Encased_Plutonium_Cell'
    # WASTE
    URANIUM_WASTE = 'Uranium_Waste'
    PLUTONIUM_WASTE = 'Plutonium_Waste'
    # SPECIAL
    PORTABLE_MINER = 'Portable_Miner'
    BLUE_POWER_SLUG = 'Blue_Power_Slug'
    YELLOW_POWER_SLUG = 'Yellow_Power_Slug'
    PURPLE_POWER_SLUG = 'Purple_Power_Slug'
    POWER_SHARD = 'Power_Shard'
    FICSIT_COUPON = 'FICSIT_Coupon'
    SMART_PLATING = 'Smart_Plating'
    VERSATILE_FRAMEWORK = 'Versatile_Framework'
    AUTOMATED_WIRING = 'Automated_Wiring'
    MODULAR_ENGINE = 'Modular_Engine'
    ADAPTIVE_CONTROL_UNIT = 'Adaptive_Control_Unit'
    ASSEMBLY_DIRECTOR_SYSTEM = 'Assembly_Director_System'
    MAGNETIC_FIELD_GENERATOR = 'Magnetic_Field_Generator'
    THERMAL_PROPULSION_ROCKET = 'Thermal_Propulsion_Rocket'
    NUCLEAR_PASTA = 'Nuclear_Pasta'
    # DROPS
    HOG_REMAINS = 'Hog_Remains'
    PLASMA_SPITTER_REMAINS = 'Plasma_Spitter_Remains'
    HATCHER_REMAINS = 'Hatcher_Remains'
    STINGER_REMAINS = 'Stringer_Remains'
