
class EConstruction:
    # production
    SMELTER = 'Smelter'
    FOUNDRY = 'Foundry'
    CONSTRUCTOR = 'Constructor'
    ASSEMBLER = 'Assembler'
    MANUFACTURER = 'Manufacturer'
    REFINERY = 'Refinery'
    PACKAGER = 'Packager'
    BLENDER = 'Blender'
    PARTICULE_ACCELERATOR = 'Particule Accelerator'
    # logistic
    CONVEYORSPLITER = 'Conveyor Spliter'
    CONVEYORMERGER = 'Conveyor Merger'
    # extractor
    MINERMK1 = 'Miner Mk.1'
    MINERMK2 = 'Miner Mk.2'
    MINERMK3 = 'Miner Mk.3'
    OILEXTRACTOR = 'Oil Extractor'
    WATEREXTRACTOR = 'Water Extractor'
    RESSOURCEWELLPRESSURIZER = 'Ressource-well Pressurizer'
    RESSOURCEWELLEXTRACTOR = 'Ressource-well Extractor'

class ERessource:
    UNKNOW = 'Not Found'
    # ORES
    LIMESTONE = 'Limestone'
    IRON_ORE = 'Iron Ore'
    COPPER_ORE = 'Copper Ore'
    CATERIUM_ORE = 'Caterium Ore'
    COAL = 'Coal'
    RAW_QUARTZ = 'Raw Quartz'
    SULFUR = 'Sulfur'
    BAUXITE = 'Bauxite'
    SAM_ORE = 'S.A.M. Ore'
    URANIUM = 'Uranium'
    # INGOTS
    IRON_INGOT = 'Iron Ingot'
    COPPER_INGOT = 'Copper Ingot'
    CATERIUM_INGOT = 'Caterium Ingot'
    STEEL_INGOT = 'Steel Ingot'
    ALUMINUM_INGOT = 'Aluminum Ingot'
    # MINERALS
    CONCRETE = 'Concrete'
    QUARTZ_CRYSTAL = 'Quartz Crystal'
    SILICA = 'Silica'
    COPPER_POWDER = 'Copper Powder'
    POLYMER_RESIN = 'Polymer Resin'
    PETROLEUM_COKE = 'Petroleum Coke'
    ALUMINUM_SCRAP = 'Aluminum Scrap'
    # ALIENS
    ALIEN_PROTEIN = 'Alien Protein'
    ALIEN_DNA_CAPSULE = 'Alien DNA Capsule'
    # LIQUIDS
    WATER = 'Water'
    CRUDE_OIL = 'Crude Oil'
    HEAVY_OIL_RESIDUE = 'Heavy Oil Residue'
    FUEL = 'Fuel'
    LIQUID_BIOFUEL = 'Liquid Biofuel'
    TURBOFUEL = 'Turbofuel'
    ALUMINA_SOLUTION = 'Alumina Solution'
    SULFURIC_ACID = 'Sulfuric Acid'
    NITRIC_ACID = 'Nitric Acid'
    # GAS
    NITROGEN_GAS = 'Nitrogen Gas'
    # STANDARD_PARTS
    IRON_ROD = 'Iron Rod'
    SCREW = 'Screw'
    IRON_PLATE = 'Iron Plate'
    REINFORCED_IRON_PLATE = 'Reinforced Iron Plate'
    COPPER_SHEET = 'Copper Sheet'
    ALCLAD_ALUMINUM_SHEET = 'Alclad Aluminum Sheet'
    ALUMINUM_CASING = 'Aluminum Casing'
    STEEL_PIPE = 'Steel Pipe'
    STEEL_BEAM = 'Steel Beam'
    ENCASED_INDUSTRIAL_BEAM = 'Encased Industrial Beam'
    MODULAR_FRAME = 'Modular Frame'
    HEAVY_MODULAR_FRAME = 'Heavy Modular Frame'
    FUSED_MODULAR_FRAME = 'Fused Modular Frame'
    FABRIC = 'Fabric'
    PLASTIC = 'Plastic'
    RUBBER = 'Rubber'
    # INDUSTRIAL_PARTS
    ROTOR = 'Rotor'
    STATOR = 'Stator'
    BATTERY = 'Battery'
    MOTOR = 'Motor'
    HEAT_SINK = 'Heat Sink'
    COOLING_SYSTEM = 'Cooling System'
    TURBO_MOTOR = 'Turbo Motor'
    # ELECTRONICS
    WIRE = 'Wire'
    CABLE = 'Cable'
    QUICKWIRE = 'Quickwire'
    CIRCUIT_BOARD = 'Circuit Board'
    AI_LIMITER = 'AI Limiter'
    HIGHSPEED_CONNECTOR = 'High-Speed Connector'
    # COMMUNICATIONS
    COMPUTER = 'Computer'
    SUPERCOMPUTER = 'Supercomputer'
    QUANTUM_COMPUTER = 'Quantum Computer'
    RADIO_CONTROL_UNIT = 'Radio Control Unit'
    CRYSTAL_OSCILLATOR = 'Crystal Oscillator'
    SUPERPOSITION_OSCILLATOR = 'Superposition Oscillator'
    # CONTAINERS
    EMPTY_CANISTER = 'Empty Canister'
    EMPTY_FLUID_TANK = 'Empty Fluid Tank'
    PRESSURE_CONVERSION_CUBE = 'Pressure Conversion Cube'
    PACKAGED_WATER = 'Packaged Water'
    PACKAGED_ALUMINA_SOLUTION = 'Packaged Alumina Solution'
    PACKAGED_SULFURIC_ACID = 'Packaged Sulfuric Acid'
    PACKAGED_NITRIC_ACID = 'Packaged Nitric Acid'
    PACKAGED_NITROGEN_GAS = 'Packaged Nitrogen Gas'
    # FUELS
    LEAVES = 'Leaves'
    MYCELIA = 'Mycelia'
    FLOWER_PETALS = 'Flower Petals'
    WOOD = 'Wood'
    BIOMASS = 'Biomass'
    COMPACTED_COAL = 'Compacted Coal'
    PACKAGED_OIL = 'Packaged Oil'
    PACKAGED_HEAVY_OIL_RESIDUE = 'Packaged Heavy Oil Residue'
    SOLID_BIOFUEL = 'Solid Biofuel'
    PACKAGED_FUEL = 'Packaged Fuel'
    PACKAGED_LIQUID_BIOFUEL = 'Packaged Liquid Biofuel'
    PACKAGED_TURBOFUEL = 'Packaged Turbofuel'
    URANIUM_FUEL_ROD = 'Uranium Fuel Rod'
    PLUTONIUM_FUEL_ROD = 'Plutonium Fuel Rod'
    # CONSUMED
    BLACK_POWDER = 'Black Powder'
    SMOKELESS_POWDER = 'Smokeless Powder'
    GAS_FILTER = 'Gas Filter'
    COLOR_CARTRIDGE = 'Color Cartridge'
    BEACON = 'Beacon'
    IODINE_INFUSED_FILTER = 'Iodine Infused Filter'
    # AMMOS
    IRON_REBAR = 'Iron Rebar'
    STUN_REBAR = 'Stun Rebar'
    SHATTER_REBAR = 'Shatter Rebar'
    EXPLOSIVE_REBAR = 'Explosive Rebar'
    RIFLE_AMMO = 'Rifle Ammo'
    HOMING_RIFLE_AMMO = 'Homing Rifle Ammo'
    TURBO_RIFLE_AMMO = 'Turbo Rifle Ammo'
    RIFLE_CARTRIDGE = 'Rifle Cartridge'
    NOBELISK = 'Nobelisk'
    GAS_NOBELISK = 'Gas Nobelisk'
    PULSE_NOBELISK = 'Pulse Nobelisk'
    CLUSTER_NOBELISK = 'Cluster Nobelisk'
    NUKE_NOBELISK = 'Nuke Nobelisk'
    # NUCLEAR
    ELECTROMAGNETIC_CONTROL_ROD = 'Electromagnetic Control Rod'
    ENCASED_URANIUM_CELL = 'Encased Uranium Cell'
    NONFISSILE_URANIUM = 'Non-fissile Uranium'
    PLUTONIUM_PELLET = 'Plutonium Pellet'
    ENCASED_PLUTONIUM_CELL = 'Encased Plutonium Cell'
    # WASTE
    URANIUM_WASTE = 'Uranium Waste'
    PLUTONIUM_WASTE = 'Plutonium Waste'
    # SPECIAL
    PORTABLE_MINER = 'Portable Miner'
    BLUE_POWER_SLUG = 'Blue Power Slug'
    YELLOW_POWER_SLUG = 'Yellow Power Slug'
    PURPLE_POWER_SLUG = 'Purple Power Slug'
    POWER_SHARD = 'Power Shard'
    FICSIT_COUPON = 'FICSIT Coupon'
    SMART_PLATING = 'Smart Plating'
    VERSATILE_FRAMEWORK = 'Versatile Framework'
    AUTOMATED_WIRING = 'Automated Wiring'
    MODULAR_ENGINE = 'Modular Engine'
    ADAPTIVE_CONTROL_UNIT = 'Adaptive Control Unit'
    ASSEMBLY_DIRECTOR_SYSTEM = 'Assembly Director System'
    MAGNETIC_FIELD_GENERATOR = 'Magnetic Field Generator'
    THERMAL_PROPULSION_ROCKET = 'Thermal Propulsion Rocket'
    NUCLEAR_PASTA = 'Nuclear Pasta'
    # DROPS
    HOG_REMAINS = 'Hog Remains'
    PLASMA_SPITTER_REMAINS = 'Plasma Spitter Remains'
    HATCHER_REMAINS = 'Hatcher Remains'
    STINGER_REMAINS = 'Stringer Remains'
